version: "2"
plugins:
  cppcheck:
    enabled: true
    config:
      check: all
      language: c
      stds:
        - c11 # Other standards C99 C89
      # Allow inline supression comments in files to remove false positives
      # EXAMPLE: // cppcheck-suppress memleak
      inline-suppr: true
      defines:
      - "F_CPU=10000000UL"
# suppressions-list: .cppcheck-suppressions
# keyword check options
# all
# Enable all checks
# style
# Check coding style
# performance
# Enable performance messages
# portability
# Enable portability messages
# information
# Enable information messages
# unusedFunction
# Check for unused functions
# missingInclude
# Warn if there are missing includes. For detailed information use --check-config

